version: 2

linters:
  disable:
    - gosec
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck

run:
  timeout: 2m

issues:
  exclude-use-default: false

output:
  format: colored-line-number
