api:
  port: ":8080"
  timeout: 5
  healthcheckInterval: 5

crypto:
  prime: "FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1"
  generator: "2"
  serverSecretKey: "863d268fe1fbedad03c347670de5580d4c44486228c0bb8108840e08b6aea204"

session:
  lifetime: 10
  addr: "vk-internship_session:50053"

user:
  addr: "vk-internship_user:50052"

listing:
  addr: "vk-internship_listing:50051"
