// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: listing.proto

package listingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0}
}

type Listing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	AuthorId      string                 `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Likes         int64                  `protobuf:"varint,9,opt,name=likes,proto3" json:"likes,omitempty"`
	IsLiked       bool                   `protobuf:"varint,10,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	IsYours       bool                   `protobuf:"varint,11,opt,name=is_yours,json=isYours,proto3" json:"is_yours,omitempty"`
	AuthorLogin   string                 `protobuf:"bytes,12,opt,name=author_login,json=authorLogin,proto3" json:"author_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{1}
}

func (x *Listing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listing) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Listing) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Listing) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Listing) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Listing) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Listing) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Listing) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *Listing) GetIsYours() bool {
	if x != nil {
		return x.IsYours
	}
	return false
}

func (x *Listing) GetAuthorLogin() string {
	if x != nil {
		return x.AuthorLogin
	}
	return ""
}

type GetAllListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	SortField     string                 `protobuf:"bytes,3,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	OnlyLiked     bool                   `protobuf:"varint,5,opt,name=only_liked,json=onlyLiked,proto3" json:"only_liked,omitempty"`
	Page          int64                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	MinPrice      int64                  `protobuf:"varint,7,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int64                  `protobuf:"varint,8,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllListingsRequest) Reset() {
	*x = GetAllListingsRequest{}
	mi := &file_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllListingsRequest) ProtoMessage() {}

func (x *GetAllListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllListingsRequest.ProtoReflect.Descriptor instead.
func (*GetAllListingsRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllListingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllListingsRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *GetAllListingsRequest) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *GetAllListingsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *GetAllListingsRequest) GetOnlyLiked() bool {
	if x != nil {
		return x.OnlyLiked
	}
	return false
}

func (x *GetAllListingsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllListingsRequest) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GetAllListingsRequest) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type GetAllListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	TotalPages    int64                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage   int64                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllListingsResponse) Reset() {
	*x = GetAllListingsResponse{}
	mi := &file_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllListingsResponse) ProtoMessage() {}

func (x *GetAllListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllListingsResponse.ProtoReflect.Descriptor instead.
func (*GetAllListingsResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *GetAllListingsResponse) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetAllListingsResponse) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

type AddListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	AuthorId      string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListingRequest) Reset() {
	*x = AddListingRequest{}
	mi := &file_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListingRequest) ProtoMessage() {}

func (x *AddListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListingRequest.ProtoReflect.Descriptor instead.
func (*AddListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{4}
}

func (x *AddListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddListingRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddListingRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddListingRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *AddListingRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type AddListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListingResponse) Reset() {
	*x = AddListingResponse{}
	mi := &file_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListingResponse) ProtoMessage() {}

func (x *AddListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListingResponse.ProtoReflect.Descriptor instead.
func (*AddListingResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{5}
}

func (x *AddListingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditListingRequest) Reset() {
	*x = EditListingRequest{}
	mi := &file_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditListingRequest) ProtoMessage() {}

func (x *EditListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditListingRequest.ProtoReflect.Descriptor instead.
func (*EditListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{6}
}

func (x *EditListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EditListingRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EditListingRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EditListingRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EditListingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingRequest) Reset() {
	*x = DeleteListingRequest{}
	mi := &file_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingRequest) ProtoMessage() {}

func (x *DeleteListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingRequest.ProtoReflect.Descriptor instead.
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteListingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLikeRequest) Reset() {
	*x = AddLikeRequest{}
	mi := &file_listing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLikeRequest) ProtoMessage() {}

func (x *AddLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLikeRequest.ProtoReflect.Descriptor instead.
func (*AddLikeRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{8}
}

func (x *AddLikeRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *AddLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLikeRequest) Reset() {
	*x = RemoveLikeRequest{}
	mi := &file_listing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLikeRequest) ProtoMessage() {}

func (x *RemoveLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLikeRequest.ProtoReflect.Descriptor instead.
func (*RemoveLikeRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveLikeRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *RemoveLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_listing_proto protoreflect.FileDescriptor

const file_listing_proto_rawDesc = "" +
	"\n" +
	"\rlisting.proto\x12\tlistingpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xe5\x02\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\tR\bauthorId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05likes\x18\t \x01(\x03R\x05likes\x12\x19\n" +
	"\bis_liked\x18\n" +
	" \x01(\bR\aisLiked\x12\x19\n" +
	"\bis_yours\x18\v \x01(\bR\aisYours\x12!\n" +
	"\fauthor_login\x18\f \x01(\tR\vauthorLogin\"\x81\x02\n" +
	"\x15GetAllListingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x12\x1d\n" +
	"\n" +
	"sort_field\x18\x03 \x01(\tR\tsortField\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\x12\x1d\n" +
	"\n" +
	"only_liked\x18\x05 \x01(\bR\tonlyLiked\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x03R\x04page\x12\x1b\n" +
	"\tmin_price\x18\a \x01(\x03R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\b \x01(\x03R\bmaxPrice\"\x8c\x01\n" +
	"\x16GetAllListingsResponse\x12.\n" +
	"\blistings\x18\x01 \x03(\v2\x12.listingpb.ListingR\blistings\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x03R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x03R\vcurrentPage\"\xb5\x01\n" +
	"\x11AddListingRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"$\n" +
	"\x12AddListingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc2\x01\n" +
	"\x12EditListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\"?\n" +
	"\x14DeleteListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x0eAddLikeRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x11RemoveLikeRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xac\x03\n" +
	"\x0eListingService\x12U\n" +
	"\x0eGetAllListings\x12 .listingpb.GetAllListingsRequest\x1a!.listingpb.GetAllListingsResponse\x12I\n" +
	"\n" +
	"AddListing\x12\x1c.listingpb.AddListingRequest\x1a\x1d.listingpb.AddListingResponse\x12>\n" +
	"\vEditListing\x12\x1d.listingpb.EditListingRequest\x1a\x10.listingpb.Empty\x12B\n" +
	"\rDeleteListing\x12\x1f.listingpb.DeleteListingRequest\x1a\x10.listingpb.Empty\x126\n" +
	"\aAddLike\x12\x19.listingpb.AddLikeRequest\x1a\x10.listingpb.Empty\x12<\n" +
	"\n" +
	"RemoveLike\x12\x1c.listingpb.RemoveLikeRequest\x1a\x10.listingpb.EmptyB\fZ\n" +
	"/listingpbb\x06proto3"

var (
	file_listing_proto_rawDescOnce sync.Once
	file_listing_proto_rawDescData []byte
)

func file_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)))
	})
	return file_listing_proto_rawDescData
}

var file_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_listing_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: listingpb.Empty
	(*Listing)(nil),                // 1: listingpb.Listing
	(*GetAllListingsRequest)(nil),  // 2: listingpb.GetAllListingsRequest
	(*GetAllListingsResponse)(nil), // 3: listingpb.GetAllListingsResponse
	(*AddListingRequest)(nil),      // 4: listingpb.AddListingRequest
	(*AddListingResponse)(nil),     // 5: listingpb.AddListingResponse
	(*EditListingRequest)(nil),     // 6: listingpb.EditListingRequest
	(*DeleteListingRequest)(nil),   // 7: listingpb.DeleteListingRequest
	(*AddLikeRequest)(nil),         // 8: listingpb.AddLikeRequest
	(*RemoveLikeRequest)(nil),      // 9: listingpb.RemoveLikeRequest
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_listing_proto_depIdxs = []int32{
	10, // 0: listingpb.Listing.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: listingpb.GetAllListingsResponse.listings:type_name -> listingpb.Listing
	2,  // 2: listingpb.ListingService.GetAllListings:input_type -> listingpb.GetAllListingsRequest
	4,  // 3: listingpb.ListingService.AddListing:input_type -> listingpb.AddListingRequest
	6,  // 4: listingpb.ListingService.EditListing:input_type -> listingpb.EditListingRequest
	7,  // 5: listingpb.ListingService.DeleteListing:input_type -> listingpb.DeleteListingRequest
	8,  // 6: listingpb.ListingService.AddLike:input_type -> listingpb.AddLikeRequest
	9,  // 7: listingpb.ListingService.RemoveLike:input_type -> listingpb.RemoveLikeRequest
	3,  // 8: listingpb.ListingService.GetAllListings:output_type -> listingpb.GetAllListingsResponse
	5,  // 9: listingpb.ListingService.AddListing:output_type -> listingpb.AddListingResponse
	0,  // 10: listingpb.ListingService.EditListing:output_type -> listingpb.Empty
	0,  // 11: listingpb.ListingService.DeleteListing:output_type -> listingpb.Empty
	0,  // 12: listingpb.ListingService.AddLike:output_type -> listingpb.Empty
	0,  // 13: listingpb.ListingService.RemoveLike:output_type -> listingpb.Empty
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_listing_proto_init() }
func file_listing_proto_init() {
	if File_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_depIdxs,
		MessageInfos:      file_listing_proto_msgTypes,
	}.Build()
	File_listing_proto = out.File
	file_listing_proto_goTypes = nil
	file_listing_proto_depIdxs = nil
}
